export const INTERMEDIATE_DUMMY_LOGS = [
  {
    id: 'ilog-001',
    type: 'students',
    fileName: 'mpc_y1_students.xlsx',
    uploadedBy: 'hodcst@sasi.ac.in',
    uploadedAt: '2026-05-18 09:12:44',
    rowsProcessed: 224,
    status: 'SUCCESS',
    errorLog: null,
  },
  {
    id: 'ilog-002',
    type: 'exams',
    fileName: 'weekly_test_5_definitions.xlsx',
    uploadedBy: 'hodcst@sasi.ac.in',
    uploadedAt: '2026-05-17 16:38:02',
    rowsProcessed: 12,
    status: 'SUCCESS',
    errorLog: null,
  },
  {
    id: 'ilog-003',
    type: 'examresults',
    fileName: 'weekly_test_5_results.xlsx',
    uploadedBy: 'priya.sharma@sasi.ac.in',
    uploadedAt: '2026-05-17 18:11:55',
    rowsProcessed: 0,
    status: 'FAILED',
    errorLog:
      'Row 14: subject column "math_q1" not declared in exam definition. Row 31: student code "INT2401099" not found in Students.',
  },
  {
    id: 'ilog-004',
    type: 'students',
    fileName: 'bipc_y2_students.csv',
    uploadedBy: 'arjun.reddy@sasi.ac.in',
    uploadedAt: '2026-05-16 11:05:30',
    rowsProcessed: 187,
    status: 'SUCCESS',
    errorLog: null,
  },
  {
    id: 'ilog-005',
    type: 'examresults',
    fileName: 'grand_test_3_results.xlsx',
    uploadedBy: 'hodcst@sasi.ac.in',
    uploadedAt: '2026-05-15 14:22:08',
    rowsProcessed: 0,
    status: 'FAILED',
    errorLog: 'Missing required column "code" for student lookup. Aborted.',
  },
]
