export const DUMMY_STUDENTS = [
  {
    id: 'std-001',
    name: 'Medimpudi Teja Sri',
    rollNo: '142203010',
    branch: 'CSE',
    isCollege: true,
    program: 'B.Tech Computer Science',
    programCode: 'BTCSE',
    joiningYear: 2022,
    parentName: 'Medimpudi Ravi Kumar',
    parentPhone: '+91 98765 43210',
  },
  {
    id: 'std-002',
    name: 'Kaduluri Jeevesh Kumar',
    rollNo: '142304006',
    branch: 'ECE',
    isCollege: true,
    program: 'B.Tech Electronics & Communication',
    programCode: 'BTECE',
    joiningYear: 2023,
    parentName: 'Kaduluri Srinivas',
    parentPhone: '+91 99887 76655',
  },
  {
    id: 'std-003',
    name: 'Saladi Sri Venkata Pranav Ganesh',
    rollNo: '142506009',
    branch: 'AI&ML',
    isCollege: true,
    program: 'B.Tech AI & ML',
    programCode: 'BTAIML',
    joiningYear: 2025,
    parentName: 'Saladi Ganesh Rao',
    parentPhone: '+91 91234 56780',
  },
  {
    id: 'std-004',
    name: 'Boppana Parnitha',
    rollNo: 'X-CBSE-021',
    branch: 'X-A',
    isCollege: false,
    program: 'Class 10 - CBSE',
    programCode: 'X-CBSE',
    joiningYear: 2024,
    parentName: 'Boppana Lakshmi',
    parentPhone: '+91 90909 80808',
  },
  {
    id: 'std-005',
    name: 'Mareedu Dhana Sri Valli',
    rollNo: 'XII-SCI-015',
    branch: 'XII-A',
    isCollege: false,
    program: 'Class 12 - Science',
    programCode: 'XII-SCI',
    joiningYear: 2023,
    parentName: 'Mareedu Suresh',
    parentPhone: '+91 88776 65544',
  },
]
